CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(20),
    address VARCHAR2(200)
);

CREATE TABLE accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    account_type VARCHAR2(20),
    balance NUMBER(18,2),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE transactions (
    txn_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER NOT NULL,
    txn_type VARCHAR2(20),
    amount NUMBER(18,2),
    txn_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);